const IMAGE =
  'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg';

export const PRODUCT_LIST = [
  {
    id: 1,
    name: 'T-Shirt',
    category: 'Clothes',
    price: 20,
    image: IMAGE,
    promotion: 0,
    quantity: 0,
  },
  {
    id: 2,
    name: 'Sneakers',
    category: 'Shoes',
    price: 50,
    image: IMAGE,
    promotion: 10,
    quantity: 0,
  },
  {
    id: 3,
    name: 'Smartphone',
    category: 'Electronics',
    price: 300,
    image: IMAGE,
    promotion: 0,
    quantity: 0,
  },
  {
    id: 4,
    name: 'Jeans',
    category: 'Clothes',
    price: 40,
    image: IMAGE,
    promotion: 0,
    quantity: 0,
  },
  {
    id: 5,
    name: 'Headphones',
    category: 'Electronics',
    price: 80,
    image: IMAGE,
    promotion: 50,
    quantity: 0,
  },
  {
    id: 6,
    name: 'Watch',
    category: 'Accessories',
    price: 150,
    image: IMAGE,
    promotion: 20,
    quantity: 0,
  },
  {
    id: 7,
    name: 'Sunglasses',
    category: 'Accessories',
    price: 60,
    image: IMAGE,
    promotion: 15,
    quantity: 0,
  },
  {
    id: 8,
    name: 'Backpack',
    category: 'Bags',
    price: 90,
    image: IMAGE,
    promotion: 5,
    quantity: 0,
  },
  {
    id: 9,
    name: 'Laptop',
    category: 'Electronics',
    price: 1000,
    image: IMAGE,
    promotion: 100,
    quantity: 0,
  },
  {
    id: 10,
    name: 'Tablet',
    category: 'Electronics',
    price: 500,
    image: IMAGE,
    promotion: 50,
    quantity: 0,
  },
  {
    id: 11,
    name: 'Gaming Mouse',
    category: 'Electronics',
    price: 40,
    image: IMAGE,
    promotion: 10,
    quantity: 0,
  },
  {
    id: 12,
    name: 'Gaming Keyboard',
    category: 'Electronics',
    price: 70,
    image: IMAGE,
    promotion: 15,
    quantity: 0,
  },
  {
    id: 13,
    name: 'Jacket',
    category: 'Clothes',
    price: 100,
    image: IMAGE,
    promotion: 20,
    quantity: 0,
  },
  {
    id: 14,
    name: 'Hiking Boots',
    category: 'Shoes',
    price: 120,
    image: IMAGE,
    promotion: 25,
    quantity: 0,
  },
  {
    id: 15,
    name: 'Desk Chair',
    category: 'Furniture',
    price: 200,
    image: IMAGE,
    promotion: 30,
    quantity: 0,
  },
  {
    id: 16,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    price: 90,
    image: IMAGE,
    promotion: 10,
    quantity: 0,
  },
  {
    id: 17,
    name: 'Water Bottle',
    category: 'Accessories',
    price: 25,
    image: IMAGE,
    promotion: 5,
    quantity: 0,
  },
  {
    id: 18,
    name: 'Running Shoes',
    category: 'Shoes',
    price: 80,
    image: IMAGE,
    promotion: 15,
    quantity: 0,
  },
  {
    id: 19,
    name: 'Yoga Mat',
    category: 'Sports',
    price: 35,
    image: IMAGE,
    promotion: 5,
    quantity: 0,
  },
  {
    id: 20,
    name: 'Dumbbells',
    category: 'Sports',
    price: 60,
    image: IMAGE,
    promotion: 10,
    quantity: 0,
  },
];
