import { CartProvider } from '@import/context/useCart';

import { Suspense } from 'react';
import { ThemeProvider } from 'react-bootstrap';
import { ToastContainer } from 'react-toastify';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Header from '@components/layout/Header';

import 'bootstrap/dist/css/bootstrap.min.css';

import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          breakpoints={['xxxl', 'xxl', 'xl', 'lg', 'md', 'sm', 'xs', 'xxs']}
          minBreakpoint="xxs">
          <Suspense>
            <CartProvider>
              <Header />
              {children}
              <ToastContainer></ToastContainer>
            </CartProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
